"""Seed ad analytics platforms (53 platforms, Tier 1-3)

Revision ID: 002
Revises: 001
Create Date: 2024-01-01 00:00:01.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Platform seed data
PLATFORMS = [
    # Tier 1 - Critical (9 platforms)
    {
        "platform_code": "meta_capi",
        "name": "Meta Conversions API (Facebook/Instagram)",
        "category": "advertising",
        "tier": 1,
        "auth_type": "access_token",
        "api_base_url": "https://graph.facebook.com/v18.0",
        "credential_schema": '{"access_token": "string", "pixel_id": "string"}',
        "description": "Meta Conversions API for Facebook and Instagram ads",
    },
    {
        "platform_code": "google_ads",
        "name": "Google Ads Conversion Tracking",
        "category": "advertising",
        "tier": 1,
        "auth_type": "oauth2",
        "api_base_url": "https://googleads.googleapis.com",
        "credential_schema": '{"customer_id": "string", "conversion_action_id": "string"}',
        "description": "Google Ads offline conversion tracking",
    },
    {
        "platform_code": "ga4",
        "name": "Google Analytics 4",
        "category": "analytics",
        "tier": 1,
        "auth_type": "api_key",
        "api_base_url": "https://www.google-analytics.com/mp/collect",
        "credential_schema": '{"measurement_id": "string", "api_secret": "string"}',
        "description": "GA4 Measurement Protocol",
    },
    {
        "platform_code": "tiktok_events",
        "name": "TikTok Events API",
        "category": "advertising",
        "tier": 1,
        "auth_type": "access_token",
        "api_base_url": "https://business-api.tiktok.com/open_api/v1.3",
        "credential_schema": '{"access_token": "string", "pixel_code": "string"}',
        "description": "TikTok Events API for conversion tracking",
    },
    {
        "platform_code": "snapchat_capi",
        "name": "Snapchat Conversions API",
        "category": "advertising",
        "tier": 1,
        "auth_type": "bearer_token",
        "api_base_url": "https://tr.snapchat.com/v2",
        "credential_schema": '{"pixel_id": "string", "access_token": "string"}',
        "description": "Snapchat Conversions API",
    },
    {
        "platform_code": "pinterest_capi",
        "name": "Pinterest Conversions API",
        "category": "advertising",
        "tier": 1,
        "auth_type": "access_token",
        "api_base_url": "https://api.pinterest.com/v5",
        "credential_schema": '{"ad_account_id": "string", "access_token": "string"}',
        "description": "Pinterest API for Conversions",
    },
    {
        "platform_code": "twitter_capi",
        "name": "Twitter/X Conversions API",
        "category": "advertising",
        "tier": 1,
        "auth_type": "oauth2",
        "api_base_url": "https://ads-api.twitter.com",
        "credential_schema": '{"pixel_id": "string", "access_token": "string"}',
        "description": "Twitter/X Conversions API",
    },
    {
        "platform_code": "linkedin_capi",
        "name": "LinkedIn Conversions API",
        "category": "advertising",
        "tier": 1,
        "auth_type": "oauth2",
        "api_base_url": "https://api.linkedin.com/v2",
        "credential_schema": '{"partner_id": "string", "access_token": "string"}',
        "description": "LinkedIn Conversions API",
    },
    {
        "platform_code": "microsoft_ads",
        "name": "Microsoft Advertising UET",
        "category": "advertising",
        "tier": 1,
        "auth_type": "oauth2",
        "api_base_url": "https://bat.bing.com",
        "credential_schema": '{"tag_id": "string"}',
        "description": "Microsoft/Bing Ads Universal Event Tracking",
    },
    # Tier 2 - Important (14 platforms)
    {
        "platform_code": "amazon_ads",
        "name": "Amazon Ads Attribution",
        "category": "advertising",
        "tier": 2,
        "auth_type": "oauth2",
        "api_base_url": "https://advertising-api.amazon.com",
        "credential_schema": '{"client_id": "string", "client_secret": "string", "profile_id": "string"}',
        "description": "Amazon Advertising Attribution API",
    },
    {
        "platform_code": "criteo",
        "name": "Criteo Events API",
        "category": "advertising",
        "tier": 2,
        "auth_type": "oauth2",
        "api_base_url": "https://api.criteo.com",
        "credential_schema": '{"client_id": "string", "client_secret": "string"}',
        "description": "Criteo Marketing Solutions",
    },
    {
        "platform_code": "reddit_capi",
        "name": "Reddit Conversions API",
        "category": "advertising",
        "tier": 2,
        "auth_type": "access_token",
        "api_base_url": "https://ads-api.reddit.com/api/v2.0",
        "credential_schema": '{"pixel_id": "string", "access_token": "string"}',
        "description": "Reddit Ads Conversions API",
    },
    {
        "platform_code": "quora_pixel",
        "name": "Quora Pixel",
        "category": "advertising",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://quora.com/ads_pixel",
        "credential_schema": '{"pixel_id": "string"}',
        "description": "Quora Ads Pixel",
    },
    {
        "platform_code": "taboola",
        "name": "Taboola Conversions",
        "category": "advertising",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://backstage.taboola.com/backstage/api/1.0",
        "credential_schema": '{"client_id": "string", "client_secret": "string"}',
        "description": "Taboola native advertising",
    },
    {
        "platform_code": "outbrain",
        "name": "Outbrain Conversions",
        "category": "advertising",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://api.outbrain.com/amplify/v0.1",
        "credential_schema": '{"marketer_id": "string", "api_key": "string"}',
        "description": "Outbrain native advertising",
    },
    {
        "platform_code": "trade_desk",
        "name": "The Trade Desk",
        "category": "advertising",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://api.thetradedesk.com/v3",
        "credential_schema": '{"advertiser_id": "string", "api_key": "string"}',
        "description": "The Trade Desk DSP",
    },
    {
        "platform_code": "dv360",
        "name": "Display & Video 360",
        "category": "advertising",
        "tier": 2,
        "auth_type": "oauth2",
        "api_base_url": "https://displayvideo.googleapis.com",
        "credential_schema": '{"partner_id": "string", "advertiser_id": "string"}',
        "description": "Google Display & Video 360",
    },
    {
        "platform_code": "adobe_analytics",
        "name": "Adobe Analytics",
        "category": "analytics",
        "tier": 2,
        "auth_type": "oauth2",
        "api_base_url": "https://analytics.adobe.io",
        "credential_schema": '{"client_id": "string", "client_secret": "string", "company_id": "string"}',
        "description": "Adobe Analytics Data Insertion API",
    },
    {
        "platform_code": "mixpanel",
        "name": "Mixpanel",
        "category": "analytics",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://api.mixpanel.com",
        "credential_schema": '{"token": "string", "api_secret": "string"}',
        "description": "Mixpanel product analytics",
    },
    {
        "platform_code": "amplitude",
        "name": "Amplitude",
        "category": "analytics",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://api2.amplitude.com",
        "credential_schema": '{"api_key": "string"}',
        "description": "Amplitude product analytics",
    },
    {
        "platform_code": "segment",
        "name": "Segment",
        "category": "cdp",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://api.segment.io/v1",
        "credential_schema": '{"write_key": "string"}',
        "description": "Segment CDP",
    },
    {
        "platform_code": "klaviyo",
        "name": "Klaviyo",
        "category": "marketing",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://a.klaviyo.com/api",
        "credential_schema": '{"api_key": "string"}',
        "description": "Klaviyo email marketing",
    },
    {
        "platform_code": "braze",
        "name": "Braze",
        "category": "marketing",
        "tier": 2,
        "auth_type": "api_key",
        "api_base_url": "https://rest.iad-01.braze.com",
        "credential_schema": '{"api_key": "string", "app_id": "string"}',
        "description": "Braze customer engagement platform",
    },
    # Tier 3 - Standard (30 platforms)
    {
        "platform_code": "heap",
        "name": "Heap Analytics",
        "category": "analytics",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://heapanalytics.com/api",
        "credential_schema": '{"app_id": "string"}',
        "description": "Heap digital analytics",
    },
    {
        "platform_code": "fullstory",
        "name": "FullStory",
        "category": "analytics",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.fullstory.com",
        "credential_schema": '{"api_key": "string", "org_id": "string"}',
        "description": "FullStory digital experience analytics",
    },
    {
        "platform_code": "hotjar",
        "name": "Hotjar",
        "category": "analytics",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.hotjar.com",
        "credential_schema": '{"site_id": "string"}',
        "description": "Hotjar behavior analytics",
    },
    {
        "platform_code": "pendo",
        "name": "Pendo",
        "category": "analytics",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://app.pendo.io/api/v1",
        "credential_schema": '{"api_key": "string"}',
        "description": "Pendo product analytics",
    },
    {
        "platform_code": "appsflyer",
        "name": "AppsFlyer",
        "category": "attribution",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api2.appsflyer.com",
        "credential_schema": '{"app_id": "string", "dev_key": "string"}',
        "description": "AppsFlyer mobile attribution",
    },
    {
        "platform_code": "adjust",
        "name": "Adjust",
        "category": "attribution",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.adjust.com",
        "credential_schema": '{"app_token": "string", "s2s_token": "string"}',
        "description": "Adjust mobile attribution",
    },
    {
        "platform_code": "branch",
        "name": "Branch",
        "category": "attribution",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api2.branch.io",
        "credential_schema": '{"branch_key": "string", "branch_secret": "string"}',
        "description": "Branch mobile attribution",
    },
    {
        "platform_code": "kochava",
        "name": "Kochava",
        "category": "attribution",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://control.kochava.com/api",
        "credential_schema": '{"app_guid": "string", "api_key": "string"}',
        "description": "Kochava attribution",
    },
    {
        "platform_code": "singular",
        "name": "Singular",
        "category": "attribution",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.singular.net/api/v1",
        "credential_schema": '{"api_key": "string"}',
        "description": "Singular attribution",
    },
    {
        "platform_code": "iterable",
        "name": "Iterable",
        "category": "marketing",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.iterable.com/api",
        "credential_schema": '{"api_key": "string"}',
        "description": "Iterable cross-channel marketing",
    },
    {
        "platform_code": "customer_io",
        "name": "Customer.io",
        "category": "marketing",
        "tier": 3,
        "auth_type": "basic_auth",
        "api_base_url": "https://track.customer.io/api/v1",
        "credential_schema": '{"site_id": "string", "api_key": "string"}',
        "description": "Customer.io messaging platform",
    },
    {
        "platform_code": "intercom",
        "name": "Intercom",
        "category": "marketing",
        "tier": 3,
        "auth_type": "access_token",
        "api_base_url": "https://api.intercom.io",
        "credential_schema": '{"access_token": "string"}',
        "description": "Intercom customer messaging",
    },
    {
        "platform_code": "hubspot",
        "name": "HubSpot",
        "category": "crm",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://api.hubapi.com",
        "credential_schema": '{"access_token": "string", "portal_id": "string"}',
        "description": "HubSpot CRM and marketing",
    },
    {
        "platform_code": "salesforce",
        "name": "Salesforce Marketing Cloud",
        "category": "crm",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://mc.exacttarget.com",
        "credential_schema": '{"client_id": "string", "client_secret": "string", "account_id": "string"}',
        "description": "Salesforce Marketing Cloud",
    },
    {
        "platform_code": "mparticle",
        "name": "mParticle",
        "category": "cdp",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://s2s.mparticle.com/v2",
        "credential_schema": '{"api_key": "string", "api_secret": "string"}',
        "description": "mParticle CDP",
    },
    {
        "platform_code": "treasure_data",
        "name": "Treasure Data",
        "category": "cdp",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.treasuredata.com",
        "credential_schema": '{"api_key": "string", "database": "string"}',
        "description": "Treasure Data enterprise CDP",
    },
    {
        "platform_code": "rudderstack",
        "name": "RudderStack",
        "category": "cdp",
        "tier": 3,
        "auth_type": "basic_auth",
        "api_base_url": "https://hosted.rudderlabs.com/v1",
        "credential_schema": '{"write_key": "string", "data_plane_url": "string"}',
        "description": "RudderStack CDP",
    },
    {
        "platform_code": "amazon_dsp",
        "name": "Amazon DSP",
        "category": "advertising",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://advertising-api.amazon.com/dsp",
        "credential_schema": '{"client_id": "string", "profile_id": "string"}',
        "description": "Amazon demand-side platform",
    },
    {
        "platform_code": "walmart_connect",
        "name": "Walmart Connect",
        "category": "advertising",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://api.advertising.walmart.com",
        "credential_schema": '{"client_id": "string", "client_secret": "string"}',
        "description": "Walmart Connect advertising",
    },
    {
        "platform_code": "instacart_ads",
        "name": "Instacart Ads",
        "category": "advertising",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://ads.instacart.com/api",
        "credential_schema": '{"client_id": "string", "client_secret": "string"}',
        "description": "Instacart Ads platform",
    },
    {
        "platform_code": "spotify_ads",
        "name": "Spotify Ad Studio",
        "category": "advertising",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://api.spotify.com",
        "credential_schema": '{"client_id": "string", "client_secret": "string"}',
        "description": "Spotify advertising",
    },
    {
        "platform_code": "yahoo_dsp",
        "name": "Yahoo DSP",
        "category": "advertising",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://api.gemini.yahoo.com",
        "credential_schema": '{"consumer_key": "string", "consumer_secret": "string"}',
        "description": "Yahoo demand-side platform",
    },
    {
        "platform_code": "mediamath",
        "name": "MediaMath",
        "category": "advertising",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.mediamath.com",
        "credential_schema": '{"api_key": "string", "organization_id": "string"}',
        "description": "MediaMath programmatic",
    },
    {
        "platform_code": "adroll",
        "name": "AdRoll",
        "category": "advertising",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.adroll.com/v1",
        "credential_schema": '{"api_key": "string", "advertisable_eid": "string"}',
        "description": "AdRoll retargeting",
    },
    {
        "platform_code": "stackadapt",
        "name": "StackAdapt",
        "category": "advertising",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.stackadapt.com",
        "credential_schema": '{"api_key": "string"}',
        "description": "StackAdapt programmatic",
    },
    {
        "platform_code": "verizon_media",
        "name": "Verizon Media DSP",
        "category": "advertising",
        "tier": 3,
        "auth_type": "oauth2",
        "api_base_url": "https://api.onebyaol.com",
        "credential_schema": '{"client_id": "string", "client_secret": "string"}',
        "description": "Verizon Media advertising",
    },
    {
        "platform_code": "lotame",
        "name": "Lotame",
        "category": "dmp",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.lotame.com/v1",
        "credential_schema": '{"client_id": "string", "api_key": "string"}',
        "description": "Lotame data management",
    },
    {
        "platform_code": "oracle_bluekai",
        "name": "Oracle BlueKai",
        "category": "dmp",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.bluekai.com",
        "credential_schema": '{"site_id": "string", "user_key": "string", "private_key": "string"}',
        "description": "Oracle BlueKai DMP",
    },
    {
        "platform_code": "liveramp",
        "name": "LiveRamp",
        "category": "identity",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.liveramp.com",
        "credential_schema": '{"api_key": "string", "secret_key": "string"}',
        "description": "LiveRamp identity resolution",
    },
    {
        "platform_code": "neustar",
        "name": "Neustar",
        "category": "identity",
        "tier": 3,
        "auth_type": "api_key",
        "api_base_url": "https://api.neustar.biz",
        "credential_schema": '{"api_key": "string", "shared_secret": "string"}',
        "description": "Neustar identity",
    },
]


def upgrade() -> None:
    # Get connection and metadata
    connection = op.get_bind()

    # Insert platforms
    for platform in PLATFORMS:
        connection.execute(
            sa.text("""
                INSERT INTO ad_analytics_platforms
                (platform_code, name, category, tier, auth_type, api_base_url, credential_schema, description, is_active)
                VALUES
                (:platform_code, :name, :category, :tier, :auth_type, :api_base_url, :credential_schema, :description, 1)
            """),
            platform,
        )


def downgrade() -> None:
    connection = op.get_bind()
    platform_codes = [p["platform_code"] for p in PLATFORMS]
    connection.execute(
        sa.text("DELETE FROM ad_analytics_platforms WHERE platform_code IN :codes"),
        {"codes": tuple(platform_codes)},
    )
